import React, { useState } from "https://esm.sh/react@18.3.1";
import { createRoot } from "https://esm.sh/react-dom@18.3.1/client";

const skills = {
  Support: { icon: "✦", title: "Support & operations", text: "Calm, structured support for difficult technical moments — from intake through a clearly documented resolution.", tags: ["Incident management", "Case ownership", "Escalations", "Knowledge base"], bars: [["Remote troubleshooting", 95], ["Root cause analysis", 92], ["Customer communication", 96], ["Technical documentation", 91]] },
  Systems: { icon: "⌘", title: "Systems & software", text: "Comfortable across the platforms and tools that power modern support teams and customer workflows.", tags: ["macOS", "Windows 10/11", "iOS / iPadOS", "Salesforce", "ServiceNow", "Git"], bars: [["Apple ecosystems", 96], ["Windows support", 88], ["SaaS platforms", 90], ["Remote tools", 93]] },
  Security: { icon: "◈", title: "Identity & security", text: "Building a cybersecurity foundation while applying a privacy-first approach to account and access support.", tags: ["MFA", "Authentication", "TCP/IP", "DNS & DHCP", "Python", "Data privacy"], bars: [["Account recovery", 93], ["Authentication & MFA", 91], ["Network diagnostics", 82], ["Cybersecurity studies", 78]] }
};

function Header(){return <header className="shell nav"><a className="monogram" href="#top" aria-label="Home">YN</a><nav className="nav-links"><a href="#experience">Experience</a><a href="#toolkit">Toolkit</a><a href="#education">Learning</a></nav><a className="nav-contact" href="mailto:you@example.com">Get in touch ↗</a></header>}
function Hero(){return <section id="top" className="shell hero"><p className="kicker">Technical Support Specialist · Cybersecurity Student</p><div className="hero-grid"><div><h1>Technical support, <em>thoughtfully</em> solved.</h1><p className="intro">A Tier 2 support specialist with 3+ years of experience untangling complex device, software, authentication, and connectivity problems — while making every customer feel heard.</p><div className="hero-actions"><a className="primary-btn" href="mailto:you@example.com">Start a conversation <span>→</span></a><a className="secondary-btn" href="#experience">View experience</a></div></div><aside className="portrait-card"><p className="portrait-label">Portfolio / 2026</p><h2>Human-first support. Technical depth.</h2><div className="mini-grid"><div><strong>Tier 2</strong><span>AppleCare advisor</span></div><div><strong>3+ yrs</strong><span>Remote support</span></div></div></aside></div><div className="stat-bar"><div className="stat"><strong>90%+</strong><span>Customer satisfaction</span></div><div className="stat"><strong>95%+</strong><span>Quality assurance</span></div><div className="stat"><strong>2</strong><span>Global tech companies</span></div></div></section>}
function Experience(){return <section id="experience" className="experience"><div className="shell section"><div className="section-head"><p className="section-number">01 / EXPERIENCE</p><h2 className="section-title">Trusted with complex problems.</h2></div><div className="roles"><article className="role"><div className="role-date"><span>JUN 2022 — MAR 2024</span><span>REMOTE</span></div><div><p className="company">APPLE INC.</p><h3>AppleCare Tier 2 Advisor</h3><p>Promoted from Tier 1 for technical performance and customer support excellence. Resolved complex macOS, iOS, Apple ID, iCloud, MFA, activation, and synchronization issues in a high-volume remote environment.</p></div><span className="tag">PROMOTED TO TIER 2</span></article><article className="role"><div className="role-date"><span>FEB 2021 — APR 2022</span><span>REMOTE</span></div><div><p className="company">INTUIT, INC.</p><h3>TurboTax Product Support Expert</h3><p>Provided real-time technical and product support for sensitive financial software across Windows and macOS, while documenting findings in Salesforce and escalating defects to engineering.</p></div><span className="tag">SAAS SUPPORT</span></article></div></div></section>}
function Toolkit(){const [active,setActive]=useState("Support");const current=skills[active];return <section id="toolkit" className="skill-zone"><div className="shell section"><div className="section-head"><p className="section-number">02 / TOOLKIT</p><div className="skill-controls">{Object.keys(skills).map(key=><button className={key===active?"active":""} onClick={()=>setActive(key)} key={key}>{key}</button>)}</div></div><div className="skill-layout"><div className="skill-bars">{current.bars.map(([label,level])=><div className="skill-row" key={label}><span>{label}</span><div className="track"><div className="fill" style={{width:`${level}%`}} /></div><strong>{level}%</strong></div>)}</div><article className="skill-card"><div className="icon">{current.icon}</div><h3>{current.title}</h3><p>{current.text}</p><ul>{current.tags.map(tag=><li key={tag}>{tag}</li>)}</ul></article></div></div></section>}
function Education(){return <section id="education" className="shell section"><div className="section-head"><p className="section-number">03 / LEARNING</p><h2 className="section-title">Always building forward.</h2></div><div className="path-grid"><article className="education-card"><p className="eyebrow">Currently pursuing</p><h3>B.S. Cybersecurity & Information Assurance</h3><p>Western Governors University · Millcreek, UT</p></article><article className="focus-card"><p className="eyebrow">Focus areas</p><h3>Support experience, security mindset.</h3><div className="module-list"><span>Identity & access</span><span>Networking</span><span>Python</span><span>Data privacy</span></div></article></div></section>}
function App(){return <div className="site"><Header/><main><Hero/><Experience/><Toolkit/><Education/><section className="contact"><div className="shell"><p className="eyebrow">Open to opportunities</p><h2>Let’s make technology feel more human.</h2><a href="mailto:you@example.com">you@example.com <span>↗</span></a></div></section></main><footer className="shell footer"><span>© 2026 Your Name</span><span>Technical Support · Cybersecurity</span></footer></div>}
createRoot(document.getElementById("root")).render(<App/>);
